# Euro12 数据集

### Step 1. 导入库

In [1]:
import numpy as np
import pandas as pd
import ssl
ssl._create_default_https_context = ssl._create_unverified_context # 全局取消证书验证

### Step 2. 导入数据，并命名为euro12： [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv).

In [31]:
url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv'
euro12 = pd.read_table(url, sep=',')
euro12.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

### Step 3. 只选择Goals列.

In [32]:
euro12['Goals']

0      4
1      4
2      4
3      5
4      3
5     10
6      5
7      6
8      2
9      2
10     6
11     1
12     5
13    12
14     5
15     2
Name: Goals, dtype: int64

### Step 4.  选择Team, Yellow Cards, Red Cards 列，并添加到一个新的DataFrame里，discipline

In [33]:
discipline = euro12[['Team', 'Yellow Cards', 'Red Cards']]
discipline

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

### Step 5. 选择进球数超过 6 的行

In [24]:
euro12[euro12.Goals>6]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18

### Step 6. 选择Team以“G”开头的行

In [25]:
euro12[euro12.Team.apply(lambda x: x[0]=='G')]

euro12[euro12.Team.str.startswith('G')]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20

### Step 7. 前3行

In [26]:
euro12.iloc[:3]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15

### Step 8. 最后3列.

In [27]:
euro12.iloc[:, -3:]

    Subs on  Subs off  Players Used
0         9         9            16
1        11        11            19
2         7         7            15
3        11        11            16
4        11        11            19
5        15        15            17
6        12        12            20
7        18        18            19
8         7         7            15
9         7         7            17
10       14        14            16
11       10        10            17
12        7         7            16
13       17        17            18
14        9         9            18
15        9         9            18

### Step 9. 选择3到7行，3到6列

In [37]:
euro12.iloc[2: 7, 2: 6]

   Shots on target  Shots off target Shooting Accuracy % Goals-to-shots
2               10                10             50.0%            20.0%
3               11                18             50.0%            17.2%
4               22                24             37.9%             6.5%
5               32                32             47.8%            15.6%
6                8                18             30.7%            19.2%

### Step 11. England, Italy, Russia的Shooting Accuracy

In [28]:
euro12.loc[euro12.Team.isin(['England', 'Italy', 'Russia']), ['Team', 'Shooting Accuracy']] # England, Italy and Russia不是索引

       Team Shooting Accuracy
3   England             50.0%
7     Italy             43.0%
12   Russia             22.5%

### Step 12. 将Team设置为索引，并选择England, Italy, Russia的Shooting Accuracy

In [29]:
euro12.set_index('Team', inplace=True)
euro12.loc[['England', 'Italy', 'Russia'], ['Shooting Accuracy']]